### ISSUE TITLE
Liquid Pipes: Implement filter for pullLiquid

### ISSUE THREAD

**Issue by HexyWitch** [alex-lawson/sb-automation#144]
Needs to be implemented like item filters. Only objects that would use it atm are: pipe spouts, liquid tanks.

Use the helper function I put in liquidpipes.lua (and fix it if it's broken).

**Comment by alex-lawson** [comment]
i've done a partial implementation of this. Liquid tanks and pipe spouts seem to be working. Objects that still need implementation/testing include:
-filter pipe
-item detector pipe
-liquid detector pipe
-valve junction
-submersion tank

**Comment by HexyWitch** [comment]
The first 4 of those would just relay that parameter, wouldn't they?

**Comment by HexyWitch** [comment]
Has this been done already? All of those except filter pipe _should_ already work.
