### ISSUE TITLE
Energy: test and evaluate energy distribution algorithm

### ISSUE THREAD

**Issue by alex-lawson** [alex-lawson/sb-automation#17]
There was a lot of disagreement on this, so let's see how well it works and where it breaks down, and we can look at revamping it in the future.

**Comment by alex-lawson** [comment]
Problem: when the network branches, the energy is split between those branches, even if some branches do not use energy (because energy needs checks do not pass through relays). Might try passing the checks through but that could get very expensive. Or it might be just fine and work great.

**Comment by HexyWitch** [comment]
Idea:

```
A relay is connected to 4 nodes and receives 100 energy.
  It splits the energy into 4 and sends 25 energy to node 1
    Node 1 accepts all the energy
  Sends 25 energy to node 2
    Node 2 does not want any energy
      Split that 25 energy into 3 and send to node 1, 3 and 4
        Node 3 refuses energy, split that 8 into 2 and send to node 1 and 4
  Sends 25 energy to node 3
    Node 3 does not want energy
      Split that 25 energy between 1 and 4
  Sends 25 energy to node 4
    Node 4 only accepts 12 energy
      Try sending the remaining amount to node 1
        Node 1 only needs 5 energy.
Return 8 energy.
```

**Comment by alex-lawson** [comment]
This algorithm should be extremely solid now. It applies the fair distribution method evenly across all valid receivers on the network, making branches/structure irrelevant to distribution. Please verify that this is actually as cool as I think.
