### ISSUE TITLE
ItemBox - Inventory gets replaced every init() with initalStorage

### ISSUE THREAD

**Issue by XspeedPL** [alex-lawson/sb-automation#20]

**Comment by HexyWitch** [comment]
I don't quite understand what the problem is. When you init the item the storage will be empty, so it replaces the empty storage with initialInventory, which is set only when you break a box. This is so it will retain the contents when you break it and then place it again.

**Comment by XspeedPL** [comment]
The init() function is called every time the object is reloaded in the world.

**Comment by XspeedPL** [comment]
Also use storageApi.setContents() provided in the newest Storage API.
