### ISSUE TITLE
Logic system require rework?

### ISSUE THREAD

**Issue by krypt-lynx** [alex-lawson/sb-automation#244]
Some things look illogical at now
For example:
Now counter reset work in different ways between it recieve binary or value signal.
Binary signal reset value once, value reset every logic tick.
Licuid detector pipe not return any value while pipe has no stream. (imo, return value must be 0, additional check is required at now)
It would be nice to have a static value element with input dialog on activation.

P.S.: Sorry, my English is terrible :)

**Comment by alex-lawson** [comment]
Not a specific issue. These kinds of suggestions / questions should be posted in the forum thread, where we (and other users) can answer them properly.
