### ISSUE TITLE
Pumps don't work in unstable version

### ISSUE THREAD

**Issue by krypt-lynx** [alex-lawson/sb-automation#251]

**Comment by alex-lawson** [comment]
After some testing, I found this to be caused by another subtle change in the Lua iteration (similar to the other bugs). I've notified the devs and will see if they're planning to fix this. If not, I'll put out a hotfix for it soon.

**Comment by krypt-lynx** [comment]
If fix is simple, can you commit it in separate branch?

**Comment by alex-lawson** [comment]
If you're curious, the fix is:
On line 80 of /objects/wired/pipe/pump/pump.lua, change `for i = 1, 7 do` to `for i = 0, 7 do`

**Comment by krypt-lynx** [comment]
Sorry, i'm close issue by accident
