### ISSUE TITLE
Energy Not Working

### ISSUE THREAD

**Issue by Zombro98** [alex-lawson/sb-automation#252]
My generator wont charge ANYTHING though i can see the power moving...help?

**Comment by alex-lawson** [comment]
This is a known issue in the 'stable' steam release. Switching to the 'unstable' release should fix the energy issues (until the 'stable' release is updated) and switching to the Starfoundry update posted today (1.3.2) should resolve further issues on the 'unstable' branch. Please leave us a reply in the discussion thread if you're still having problems after switching to the 'unstable' release and Starfoundry 1.3.2, and we'll see what we can do to help!
