### ISSUE TITLE
Balance Energy Usage

### ISSUE THREAD

**Issue by alex-lawson** [alex-lawson/sb-automation#39]
Currenty fuelToEnergy conversion is 100.

Objects which use energy:
- Basic Generator (generation rate)
- Battery Rack (charge/discharge rates)
- Battery (storage capacity)
- Powered Smelter (consumption rate)
- Magnetizer (magnetize cost)
- Positive Electromagnet (consumption rate)
- Negative Electomagnet (consumption rate)
- Advanced Electromagnet (consumption rate)
- Jump Pad (bounce cost)
- Levitation Pad (consumption rate)
- Air Fan (consumption rate)
- Conveyor Belt (consumption rate)
- Liquid Extractor (extraction cost)
- Pump (pump cost)

**Comment by PenguinToast** [comment]
Just a note, the magnetizer currently has an energy cost per monster magnetized rather than a consumption rate

**Comment by alex-lawson** [comment]
Thanks, fixed that.
