### ISSUE TITLE
Pipes: consider combining inbound + outbound nodes

### ISSUE THREAD

**Issue by alex-lawson** [alex-lawson/sb-automation#4]
After realizing that the pump had to be reversible, I'm not sure that it's necessary to separate outbound and inbound liquid/item nodes. Removing this distinction would reduce complexity of the API and its usage, and should improve performance for objects which currently implement overlapping inbound and outbound nodes.

Does this analysis make sense? What disadvantages or limitations might result from this change?

**Comment by HexyWitch** [comment]
Can probably combine them without any issues

**Comment by HexyWitch** [comment]
Doing this now

**Comment by HexyWitch** [comment]
Done, all objects now use simply itemNodes or liquidNodes
