### ISSUE TITLE
Pipes: attempt foreground walk after background walk fails (maybe)

### ISSUE THREAD

**Issue by alex-lawson** [alex-lawson/sb-automation#5]

**Comment by alex-lawson** [comment]
On second thought, I'm not sure how I feel about this. We may need a better system for handling overlapping of foreground + background pipes.

**Comment by HexyWitch** [comment]
I'm thinking it could prioritize pipes on the same layer. So walking from a foreground pipe it checks foreground, and if it finds nothing there it checks background.

EDIT: That way pipes could run past each other and still function individually, and you can also switch freely between background and foreground.

**Comment by HexyWitch** [comment]
This has been resolved.
