### ISSUE TITLE
Liquid Extractor: rework mechanics to avoid collision weirdness

### ISSUE THREAD

**Issue by alex-lawson** [alex-lawson/sb-automation#64]

**Comment by HexyWitch** [comment]
Can make a separate object that contains all the sprites for the different blocks, and use tags to set the block type and damage amount. This way we can set it to have like 1000 health as well to keep players from breaking it. Can we damage objects through damageTiles?

**Comment by alex-lawson** [comment]
I was thinking about a solution like this yesterday. Seemed like it might be useful in a number of different applications as a proxy for materials. We could add a separate animation layer for the damage in order to make it completely controllable.

**Comment by HexyWitch** [comment]
extractorblock is in the same folder as extractor, could probably be renamed blockproxy or something.
