### ISSUE TITLE
Liquid Tank: allow input/output from either direction

### ISSUE THREAD

**Issue by alex-lawson** [alex-lawson/sb-automation#72]
The tank should allow input or output from either pipe connection, and should passively output if connected to a pipe spout, but not if connected to a pump.

**Comment by alex-lawson** [comment]
When chaining tanks together directly, should probably do something like passively balance the levels (assuming liquid types match)

**Comment by HexyWitch** [comment]
Does not balance levels, instead if behaves slightly weirdly. Good enough!
