### ISSUE TITLE
Pipe walking behavior (Loops)

### ISSUE THREAD

**Issue by HexyWitch** [alex-lawson/sb-automation#8]
When pipes are looped like this http://i.imgur.com/8FoxDnC.png they will not connect.

Can be fixed pretty easily, but then another problem arises. Leaving this here for now.

**Comment by alex-lawson** [comment]
- for visitedTiles use visitedTiles[tile[1].."."..tile[2]] as you only need to check for one key
- The looping and newVisitTiles could work differently. When only using the while loop and the first element of tilesToVisit you can use table.remove and table.add to firstly walk one pipe to the end and then go on to the next. That way we can get informations from different pipes and store them with each node. See in EHD pipe api.
